server:
  port: 8086
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Proyecto3
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: jjdasndjnaskjdnuasdnjkndaskjndajksndkjajasfasdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsfd
springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui/index.html