spring:
  cloud:
    gateway:
      routes:
        - id: auth-route
          uri: http://localhost:8080
          predicate:
            - Path=/v1/auth/**
        - id: user-route
          uri: https://localhost:8081
          predicate:
            - Path=/v1/user/**
          filters:
            - AuthenticationFilter
        - id: games-route
          uri: https://localhost:8082
          predicate:
            -Path=/v1/games/**
          filters:
            -AuthenticationFilter
  endpoints:
    web:
      exposure:
        includes: "*"
  endepoint:
    health:
      show-details: always
    gateway:
      enabled: true
server:
  port: 8083